# Site settings
title:          Haandol
tagline:        Vincent Lee
url:            "http://haandol.github.io"
baseurl:        /

sass:
  style:        compressed

# Build settinga
markdown:       kramdown
highlighter:    rouge

# Custom vars
author:
  name:         'Vincent Lee'
