# Site settings
title:          Haandol
tagline:        TL;DR
url:            "https://haandol.github.io"
baseurl:        /
issueurl:       "https://github.com/haandol/haandol.github.com/issues"

sass:
  style:        compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Build settinga
markdown:       kramdown
highlighter:    rouge

paginate:       8
paginate_path:  /posts/page:num

# Custom vars
author:
  name:         'DongGyun Lee'
