# Site settings
title:          Haandol
tagline:        Machine Learning For Dummies
url:            "http://haandol.github.io"
baseurl:        /
issueurl:       "https://github.com/haandol/haandol.github.com"

sass:
  style:        compressed

# Build settinga
markdown:       kramdown
highlighter:    rouge

# Custom vars
author:
  name:         'Vincent Lee'
