# Site settings
title:          Haandol
description:    Vincent Lee
url:            "http://haandol.github.io"

# Build settinga
markdown:       kramdown
highlighter:    pygments

# Custom vars
author:
  name:         'Vincent Lee'
